base_url = "https://lupine-software.com"
title = "Lupine Software LLC"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

languages = []

[extra]
description = "The website of Lupine Software LLC. We develop software."
author = "Lupine Software LLC"
keywords = "Lupine Software"
